#debug: true

server:
  port: 5000
  servlet:
    context-path: /car_rental

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://***:3306/car_rental?characterEncoding=utf8&useSSL=true
    username: root
    password: ***
  redis:
    host: ***
    password: ***
  web:
    resources:
      static-locations: classpath:/webapp/
  mvc:
    static-path-pattern: /resources/**

token:
  expire-time: 7200

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

